### ISSUE TITLE
Wrong value shown when using "tags" option with initial value of null

### ISSUE THREAD

**Issue by chipshort** [tealpartners/ng-select2#30]
```html
<ng-select2
	[width]="100"
	[options]="{ tags: true }"
	[formControl]="formControl"
	[data]="exampleData"
	[placeholder]="'Please select a fruit...'">
</ng-select2>

<p>{{formControl.value}}</p>
```
```typescript
formControl = new FormControl();
exampleData = [
	{
		id: 'basic1',
		text: 'Basic 1'
	},
	{
		id: 'basic2',
		disabled: true,
		text: 'Basic 2'
	},
	{
		id: 'basic3',
		text: 'Basic 3'
	},
	{
		id: 'basic4',
		text: 'Basic 4'
	}
];
```

Steps to reproduce:
1. Enter a custom text that matches none of the items in `exampleData`
2. Do *not* confirm the entered text
3. Click somewhere else to hide the dropdown

Result:
The select looks as if the first element of `exampleData` is selected, but the actual value of the formControl remains null and `valueChanged` is also not fired.

Note: There is also some more weirdness going on here depending on the text entered in Step 1.
If I enter just "a" and click away, nothing happens at first, but when I click on the select, it suddenly shows the first element again.

**Comment by icecoldfire** [comment]
I can't reproduce this issue. If the issue still exists please attach a video file and a working code example of the issue. 

I tried it already with this code: https://github.com/tealpartners/ng-select2/commit/3ec8b27c8c70542d82342545fed63213db507106

**Comment by chipshort** [comment]
The issue still exists with the code from above. The commit you referenced does not seem to contain the tags option.
Here is a StackBlitz: https://stackblitz.com/edit/ng-select2-mvuh6s?file=src/app/app.component.html
and the corresponding video: 

https://user-images.githubusercontent.com/4466937/107212113-c311be00-6a06-11eb-8631-339e46a444ca.mp4

**Comment by icecoldfire** [comment]
Fixed in version 1.2.5

If there still problems please reopen this issue, have a nice day!

**Comment by chipshort** [comment]
That did not fix the problem at all (as evident using the same stackblitz with updated version)
The problem is not the null value, but that the select shows a different value than what the FormControl actually contains.
The expected behaviour here is that the select should either:
- go back to being empty and showing the placeholder, or
- the FormControl should get updated with the new value

It is not possible for me to reopen an issue that a collaborator closed.

**Comment by icecoldfire** [comment]
I created a fix but now it throws this error:

`ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'basic1'.`

This looks logical that you can't let select 2 update the value without a user input. If you have an better fix please open a PR.

**Comment by icecoldfire** [comment]
# This package is archived and no longer maintained 
You can use [@ng-select/ng-select](https://github.com/ng-select/ng-select) as replacement.
